import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/LegalPage";
import { company } from "@/lib/data";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Nachi Tekneka collects, uses and protects the personal information you share with us through nachitekneka.com.",
};

const UPDATED = "04 August 2026";

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      eyebrow="Privacy Policy"
      title={
        <>
          Your data, <span className="text-brand-gradient">handled with care</span>
        </>
      }
      updated={UPDATED}
    >
      <LegalSection number="01" title="Who we are">
        <p>
          Nachi Tekneka (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is a
          solution provider for the spinning industry, headquartered at 129A, Thotta
          Salai East, Power House Road, Perur Village, Coimbatore – 641 010, Tamil
          Nadu, India, with affiliated operations Nachi Tekneka USA LLC (Sheridan,
          Wyoming, USA) and Indmex Technology S.A DE C.V. (Cuautitlan Izcalli,
          Mexico). This policy explains how we handle personal information collected
          through <strong>nachitekneka.com</strong>.
        </p>
      </LegalSection>

      <LegalSection number="02" title="Information we collect">
        <p>We collect only what you choose to share with us:</p>
        <ul>
          <li>
            <strong>Enquiry details</strong> — when you use our contact form: your
            name, company, email address, phone number, area of interest and message.
          </li>
          <li>
            <strong>Job application details</strong> — when you apply through our
            careers page: your name, email address, phone number, location, the
            position applied for, experience level, cover note and resume/CV file.
          </li>
          <li>
            <strong>Direct communications</strong> — information you share when you
            call, email or message us on WhatsApp.
          </li>
          <li>
            <strong>Technical data</strong> — standard server logs (such as IP
            address, browser type and pages visited) generated by our hosting
            provider for security and operation of the website.
          </li>
        </ul>
      </LegalSection>

      <LegalSection number="03" title="How we use your information">
        <ul>
          <li>To respond to your enquiries and prepare quotations.</li>
          <li>To evaluate job applications and manage recruitment.</li>
          <li>To deliver, support and improve our products and services.</li>
          <li>To meet legal, accounting or regulatory requirements.</li>
        </ul>
        <p>
          We do <strong>not</strong> sell, rent or trade your personal information,
          and we do not use it for third-party advertising.
        </p>
      </LegalSection>

      <LegalSection number="04" title="How your information is shared">
        <p>Your information is shared only where necessary to serve you:</p>
        <ul>
          <li>
            <strong>Service providers</strong> — our website is hosted on Vercel and
            form submissions are delivered to our mailboxes via Resend, an email
            delivery service. These providers process data on our behalf.
          </li>
          <li>
            <strong>Our group offices</strong> — enquiries may be handled by the
            Nachi Tekneka office (India, USA or Mexico) best placed to serve you.
          </li>
          <li>
            <strong>Legal requirements</strong> — where disclosure is required by
            law or to protect our legal rights.
          </li>
        </ul>
      </LegalSection>

      <LegalSection number="05" title="Data retention">
        <p>
          We keep enquiry details for as long as needed to handle your request and
          maintain our business relationship. Job application details, including
          resumes, are kept for the duration of the recruitment process and, unless
          you ask otherwise, for a reasonable period afterwards so we can consider
          you for future openings.
        </p>
      </LegalSection>

      <LegalSection number="06" title="Security">
        <p>
          We use reputable infrastructure providers, encrypted connections (HTTPS)
          and access controls to protect your information. No method of transmission
          or storage is completely secure, but we take commercially reasonable
          measures to safeguard your data.
        </p>
      </LegalSection>

      <LegalSection number="07" title="Your rights">
        <p>
          You may request access to, correction of, or deletion of the personal
          information we hold about you, or withdraw a job application, at any time
          by writing to{" "}
          <a href={`mailto:${company.email}`}>{company.email}</a>. We will respond
          within a reasonable timeframe.
        </p>
      </LegalSection>

      <LegalSection number="08" title="Cookies">
        <p>
          We do not use advertising or tracking cookies. Our hosting infrastructure
          may set strictly necessary cookies required for the website to function
          and remain secure.
        </p>
      </LegalSection>

      <LegalSection number="09" title="Third-party links">
        <p>
          Our website contains links to third-party services such as WhatsApp. Once
          you leave our website, the privacy practices of those services apply — we
          encourage you to review their policies.
        </p>
      </LegalSection>

      <LegalSection number="10" title="Children's privacy">
        <p>
          Our website and services are intended for businesses and professionals. We
          do not knowingly collect personal information from children.
        </p>
      </LegalSection>

      <LegalSection number="11" title="Changes to this policy">
        <p>
          We may update this policy from time to time. The &ldquo;Last updated&rdquo;
          date at the top of this page shows when it was last revised. Continued use
          of the website after changes means you accept the updated policy.
        </p>
      </LegalSection>

      <LegalSection number="12" title="Contact us">
        <p>
          Questions about this policy or your data? Contact us at{" "}
          <a href={`mailto:${company.email}`}>{company.email}</a> or{" "}
          <a href={`tel:${company.phone.replace(/\s/g, "")}`}>{company.phone}</a>,
          or visit our <Link href="/contact">contact page</Link>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
